// yFiles-for-HTML-Complete-2.5.0.3-Evaluation/demos-js/toolkit/angular/src/app/app.component.ts
/****************************************************************************
 ** @license
 ** This demo file is part of yFiles for HTML 2.5.0.3.
 ** Copyright (c) 2000-2023 by yWorks GmbH, Vor dem Kreuzberg 28,
 ** 72070 Tuebingen, Germany. All rights reserved.
 **
 ** yFiles demo files exhibit yFiles for HTML functionalities. Any redistribution
 ** of demo files in source code or binary form, with or without
 ** modification, is not permitted.
 **
 ** Owners of a valid software license for a yFiles for HTML version that this
 ** demo is shipped with are allowed to use the demo source code as basis
 ** for their own yFiles for HTML powered applications. Use of such programs is
 ** governed by the rights and conditions as set out in the yFiles for HTML
 ** license agreement.
 **
 ** THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
 ** WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ** MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 ** NO EVENT SHALL yWorks BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 ** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ** TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 ** PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 ** LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 ** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 ** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **
 ***************************************************************************/
import {
  AfterViewInit,
  ApplicationRef,
  Component,
  ComponentFactoryResolver,
  Injector,
  NgZone
} from '@angular/core'
import {
  GraphComponent,
  IArrow,
  ICommand,
  IGraph,
  INode,
  LayoutExecutorAsync,
  OrganicEdgeRouter,
  PolylineEdgeStyle,
  Size,
  TreeLayout,
  TreeReductionStage
} from 'yfiles'
import { EDGE_DATA, NODE_DATA } from './data'
import { Person } from './person'
import { NodeComponentStyle } from './NodeComponentStyle'
import { GraphComponentService } from './services/graph-component.service'
import GraphSearch from '../utils/GraphSearch'
import { BrowserDetection } from '../utils/BrowserDetection'
import { zoomDetail, zoomIntermediate } from './node.component'

const ieVersion = BrowserDetection.ieVersion
const useWebWorkerLayout = !ieVersion || ieVersion > 11

// Run layout calculation on a Web Worker
let layoutWorker: Worker
if (useWebWorkerLayout && typeof Worker !== 'undefined') {
  // @ts-ignore
  layoutWorker = new Worker(new URL('./layout.worker.ts', import.meta.url), { type: 'module' })
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements AfterViewInit {
  title = 'app'

  public currentPerson?: Person
  private graphComponent!: GraphComponent
  searchString = ''
  graphSearch!: GraphSearch

  constructor(
    private _injector: Injector,
    private _resolver: ComponentFactoryResolver,
    private _appRef: ApplicationRef,
    private _zone: NgZone,
    private _graphComponentService: GraphComponentService
  ) {}

  ngAfterViewInit() {
    this.graphComponent = this._graphComponentService.getGraphComponent()

    // specify node and edge styles for newly created items
    this.setDefaultStyles(this.graphComponent.graph)

    // hook up the properties view panel with the current item of the graph
    this.graphComponent.addCurrentItemChangedListener(() => {
      this._zone.run(() => {
        this.currentPerson = this.graphComponent.currentItem!.tag
      })
    })

    // create a sample graph from data
    createSampleGraph(this.graphComponent.graph)
    this.graphComponent.fitGraphBounds()

    // Since the node component style runs "outside of angular", we have to
    // trigger change detection manually if the level of detail needs to change.
    let oldZoom = this.graphComponent.zoom
    this.graphComponent.addZoomChangedListener((sender, evt) => {
      const newZoom = this.graphComponent.zoom
      if (
        (newZoom > zoomDetail && oldZoom <= zoomDetail) ||
        (newZoom <= zoomDetail && oldZoom > zoomDetail) ||
        (newZoom > zoomIntermediate && oldZoom <= zoomIntermediate) ||
        (newZoom <= zoomIntermediate && oldZoom > zoomIntermediate)
      ) {
        this._appRef.tick()
      }
      oldZoom = newZoom
    })

    // Run the layout animation outside angular zone, so no change detection
    // is initiated for listeners registered during the layout process.
    this._zone.runOutsideAngular(() => {
      // arrange the graph elements in a tree-like fashion
      runLayout(this.graphComponent)
    })

    // register the graph search
    this.graphSearch = new PersonSearch(this.graphComponent)
  }

  private setDefaultStyles(graph: IGraph) {
    graph.nodeDefaults.size = new Size(285, 100)
    graph.nodeDefaults.style = new NodeComponentStyle(
      this._injector,
      this._resolver,
      this._appRef,
      this._zone
    )

    graph.edgeDefaults.style = new PolylineEdgeStyle({
      stroke: '2px rgb(170, 170, 170)',
      targetArrow: IArrow.NONE
    })
  }

  zoomIn() {
    ICommand.INCREASE_ZOOM.execute(null, this.graphComponent)
  }

  zoomOriginal() {
    ICommand.ZOOM.execute(1, this.graphComponent)
  }

  zoomOut() {
    ICommand.DECREASE_ZOOM.execute(null, this.graphComponent)
  }

  fitContent() {
    ICommand.FIT_GRAPH_BOUNDS.execute(null, this.graphComponent)
  }

  onSearchInput(query: string) {
    this.graphSearch.updateSearch(query)
  }
}

function createSampleGraph(graph: IGraph): void {
  const nodeMap: { [name: string]: INode } = {}

  NODE_DATA.forEach(nodeData => {
    nodeMap[nodeData.name] = graph.createNode({
      tag: new Person(nodeData)
    })
  })

  EDGE_DATA.forEach(({ from, to }) => {
    const fromNode = nodeMap[from]
    const toNode = nodeMap[to]
    if (fromNode && toNode) {
      graph.createEdge(fromNode, toNode)
    }
  })
}

async function runLayout(graphComponent: GraphComponent): Promise<void> {
  if (layoutWorker != null) {
    // run layout calculation in a Web Worker thread

    // helper function that performs the actual message passing to the web worker
    function webWorkerMessageHandler(data: unknown): Promise<any> {
      return new Promise(resolve => {
        layoutWorker.onmessage = (e: any) => resolve(e.data)
        layoutWorker.postMessage(data)
      })
    }

    // create an asynchronous layout executor that calculates a layout on the worker
    const executor = new LayoutExecutorAsync({
      messageHandler: webWorkerMessageHandler,
      graphComponent,
      duration: '1s',
      easedAnimation: true,
      animateViewport: true
    })

    await executor.start()
  } else {
    // just run the layout calculation in the main thread
    const treeLayout = new TreeLayout()
    const treeReductionStage = new TreeReductionStage()
    treeReductionStage.nonTreeEdgeRouter = new OrganicEdgeRouter()
    treeReductionStage.nonTreeEdgeSelectionKey = OrganicEdgeRouter.AFFECTED_EDGES_DP_KEY

    treeLayout.appendStage(treeReductionStage)

    await graphComponent.morphLayout(treeLayout, '1s')
  }
}

class PersonSearch extends GraphSearch {
  matches(node: INode, text: string): boolean {
    if (node.tag instanceof Person) {
      const person = node.tag
      return person.name.toLowerCase().indexOf(text.toLowerCase()) !== -1
    }
    return false
  }
}

// yFiles-for-HTML-Complete-2.5.0.3-Evaluation/demos-js/toolkit/react/src/App.jsx
/****************************************************************************
 ** @license
 ** This demo file is part of yFiles for HTML 2.5.0.3.
 ** Copyright (c) 2000-2023 by yWorks GmbH, Vor dem Kreuzberg 28,
 ** 72070 Tuebingen, Germany. All rights reserved.
 **
 ** yFiles demo files exhibit yFiles for HTML functionalities. Any redistribution
 ** of demo files in source code or binary form, with or without
 ** modification, is not permitted.
 **
 ** Owners of a valid software license for a yFiles for HTML version that this
 ** demo is shipped with are allowed to use the demo source code as basis
 ** for their own yFiles for HTML powered applications. Use of such programs is
 ** governed by the rights and conditions as set out in the yFiles for HTML
 ** license agreement.
 **
 ** THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
 ** WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ** MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 ** NO EVENT SHALL yWorks BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 ** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ** TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 ** PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 ** LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 ** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 ** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **
 ***************************************************************************/
import React, { Component } from 'react'
import './App.css'
import ReactGraphComponent from './components/ReactGraphComponent.jsx'
import DemoDescription from './components/DemoDescription.jsx'
import yLogo from './assets/ylogo.svg'
import DemoDataPanel from './components/DemoDataPanel.jsx'

export default class App extends Component {
  constructor(props) {
    super(props)
    this.state = {
      graphData: {
        nodesSource: [
          {
            id: 0,
            name: 'Node 0'
          },
          {
            id: 1,
            name: 'Node 1'
          },
          {
            id: 2,
            name: 'Node 2'
          }
        ],
        edgesSource: [
          {
            fromNode: 0,
            toNode: 1
          },
          {
            fromNode: 0,
            toNode: 2
          }
        ]
      }
    }
  }

  addNode() {
    const newIdx =
      this.state.graphData.nodesSource.reduce((maxId, item) => Math.max(maxId, item.id), 0) + 1
    const parentNodeIdx = Math.floor(Math.random() * this.state.graphData.nodesSource.length)
    this.setState(state => {
      const nodesSource = state.graphData.nodesSource.concat({
        id: newIdx,
        name: `Node ${newIdx}`
      })

      // Create an edge if the graph was not empty
      let edgesSource = state.graphData.edgesSource
      if (parentNodeIdx > -1) {
        edgesSource = state.graphData.edgesSource.concat({
          fromNode: nodesSource[parentNodeIdx].id,
          toNode: newIdx
        })
      }

      return {
        graphData: {
          nodesSource,
          edgesSource
        }
      }
    })
  }

  removeNode() {
    this.setState(state => {
      const randomNodeIdx = Math.floor(Math.random() * this.state.graphData.nodesSource.length)
      const newNodesSource = [...state.graphData.nodesSource]
      newNodesSource.splice(randomNodeIdx, 1)

      const nodeId = this.state.graphData.nodesSource[randomNodeIdx].id
      const newEdgesSource = state.graphData.edgesSource.filter(
        edge => edge.fromNode !== nodeId && edge.toNode !== nodeId
      )
      return {
        graphData: {
          nodesSource: newNodesSource,
          edgesSource: newEdgesSource
        }
      }
    })
  }

  resetData() {
    this.setState({
      graphData: {
        nodesSource: [
          {
            id: 0,
            name: 'Node 0'
          },
          {
            id: 1,
            name: 'Node 1'
          },
          {
            id: 2,
            name: 'Node 2'
          }
        ],
        edgesSource: [
          {
            fromNode: 0,
            toNode: 1
          },
          {
            fromNode: 0,
            toNode: 2
          }
        ]
      }
    })
  }

  render() {
    return (
      <div className="App">
        <aside className="demo-sidebar left">
          <DemoDescription />
        </aside>
        <aside className="demo-sidebar right">
          <DemoDataPanel
            graphData={this.state.graphData}
            onAddNode={() => this.addNode()}
            onRemoveNode={() => this.removeNode()}
          />
        </aside>

        <div className="demo-content">
          <div className="demo-header">
            <a
              href="https://www.yworks.com/products/yfiles"
              target="_blank"
              rel="noopener noreferrer"
            >
              <img src={yLogo} className="demo-y-logo" alt="yWorks Logo" />
            </a>
            <a
              href="https://www.yworks.com/products/yfiles"
              target="_blank"
              rel="noopener noreferrer"
            >
              yFiles for HTML
            </a>
            <a
              href="../../../README.html"
              target="_blank"
              className={'demo-title'}
              rel="noopener noreferrer"
            >
              Demos
            </a>
            <span className="demo-title">React Demo</span>
          </div>

          <ReactGraphComponent
            graphData={this.state.graphData}
            onResetData={() => this.resetData()}
          />
        </div>
      </div>
    )
  }
}
