// yFiles-for-HTML-Complete-2.5.0.3-Evaluation/demos-js/toolkit/react/src/components/GraphOverviewComponent.jsx
/****************************************************************************
 ** @license
 ** This demo file is part of yFiles for HTML 2.5.0.3.
 ** Copyright (c) 2000-2023 by yWorks GmbH, Vor dem Kreuzberg 28,
 ** 72070 Tuebingen, Germany. All rights reserved.
 **
 ** yFiles demo files exhibit yFiles for HTML functionalities. Any redistribution
 ** of demo files in source code or binary form, with or without
 ** modification, is not permitted.
 **
 ** Owners of a valid software license for a yFiles for HTML version that this
 ** demo is shipped with are allowed to use the demo source code as basis
 ** for their own yFiles for HTML powered applications. Use of such programs is
 ** governed by the rights and conditions as set out in the yFiles for HTML
 ** license agreement.
 **
 ** THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
 ** WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ** MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 ** NO EVENT SHALL yWorks BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 ** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ** TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 ** PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 ** LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 ** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 ** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **
 ***************************************************************************/
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import './GraphOverviewComponent.css'
import { GraphComponent, GraphOverviewComponent } from 'yfiles'

export default class ReactGraphOverviewComponent extends Component {
  constructor(props) {
    super(props)
    this.div = React.createRef()
  }

  async componentDidMount() {
    this.graphOverviewComponent = new GraphOverviewComponent(
      this.div.current,
      this.props.graphComponent
    )
  }

  render() {
    return (
      <div className="overview-container">
        <div className="overview-title">Overview</div>
        <div className="graph-overview-component" ref={this.div} />
      </div>
    )
  }
}

ReactGraphOverviewComponent.propTypes = {
  graphComponent: PropTypes.instanceOf(GraphComponent)
}

// yFiles-for-HTML-Complete-2.5.0.3-Evaluation/demos-js/toolkit/angular/src/app/graph-overview-component/graph-overview-component.component.ts
/****************************************************************************
 ** @license
 ** This demo file is part of yFiles for HTML 2.5.0.3.
 ** Copyright (c) 2000-2023 by yWorks GmbH, Vor dem Kreuzberg 28,
 ** 72070 Tuebingen, Germany. All rights reserved.
 **
 ** yFiles demo files exhibit yFiles for HTML functionalities. Any redistribution
 ** of demo files in source code or binary form, with or without
 ** modification, is not permitted.
 **
 ** Owners of a valid software license for a yFiles for HTML version that this
 ** demo is shipped with are allowed to use the demo source code as basis
 ** for their own yFiles for HTML powered applications. Use of such programs is
 ** governed by the rights and conditions as set out in the yFiles for HTML
 ** license agreement.
 **
 ** THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
 ** WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ** MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 ** NO EVENT SHALL yWorks BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 ** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ** TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 ** PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 ** LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 ** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 ** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **
 ***************************************************************************/
import { AfterViewInit, Component, ElementRef, NgZone, ViewChild } from '@angular/core'
import { GraphComponent, GraphOverviewComponent } from 'yfiles'
import { GraphComponentService } from '../services/graph-component.service'

@Component({
  selector: 'app-graph-overview-component',
  templateUrl: './graph-overview-component.component.html',
  styleUrls: ['./graph-overview-component.component.css']
})
export class GraphOverviewComponentComponent implements AfterViewInit {
  @ViewChild('graphOverviewComponentRef') graphOverviewComponentRef!: ElementRef
  graphOverviewComponent!: GraphOverviewComponent
  private readonly graphComponent: GraphComponent
  constructor(private zone: NgZone, graphComponentService: GraphComponentService) {
    this.graphComponent = graphComponentService.getGraphComponent()
  }

  ngAfterViewInit(): void {
    this.initializeOverview(this.graphComponent)
  }

  private initializeOverview(graphComponent: GraphComponent): void {
    // instantiate a new GraphOverviewComponent
    this.zone.runOutsideAngular(() => {
      this.graphOverviewComponent = new GraphOverviewComponent(
        '#graph-overview-component',
        graphComponent
      )
    })
  }
}
